# -*- coding: utf-8 -*-
"""Project - Bangla News Summarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eo-bQ5kBrnfutiKL0TnmKNqO1Kd0R4vj
"""

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_DIR = "/content/drive/MyDrive/BanglaT5_Project"

os.makedirs(BASE_DIR, exist_ok=True)
os.makedirs(f"{BASE_DIR}/cache", exist_ok=True)
os.makedirs(f"{BASE_DIR}/checkpoints", exist_ok=True)
os.makedirs(f"{BASE_DIR}/model", exist_ok=True)
os.makedirs(f"{BASE_DIR}/logs", exist_ok=True)

BASE_DIR

"""**Force HuggingFace + PyTorch cache to Google Drive**


"""

import os

# Redirect HuggingFace cache
os.environ["HF_HOME"] = f"{BASE_DIR}/cache"
os.environ["TRANSFORMERS_CACHE"] = f"{BASE_DIR}/cache"

# Disable W&B entirely
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "offline"
os.environ["WANDB_DIR"] = f"{BASE_DIR}/logs"

# Optional: reduce PyTorch multiprocessing warnings
os.environ["TOKENIZERS_PARALLELISM"] = "false"

print("Cache directory:", os.environ["HF_HOME"])

"""**Install required libraries**"""

!pip install transformers datasets sentencepiece rouge-score gradio

"""**Load dataset (article.txt & summary.txt)**"""

import pandas as pd

article_path = f"{BASE_DIR}/article.txt"
summary_path = f"{BASE_DIR}/summary.txt"

with open(article_path, "r") as f:
    articles = [line.strip() for line in f.readlines()]

with open(summary_path, "r") as f:
    summaries = [line.strip() for line in f.readlines()]

df = pd.DataFrame({"article": articles, "summary": summaries})
df.head(), len(df)

"""**Split train/validation**"""

from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

train_df.shape, val_df.shape

"""**Convert to HuggingFace Dataset**"""

from datasets import Dataset

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)

"""**Load BanglaT5 model & tokenizer (stored into Drive cache)**"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "csebuetnlp/banglat5"

tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=f"{BASE_DIR}/cache")
model = AutoModelForSeq2SeqLM.from_pretrained(model_name, cache_dir=f"{BASE_DIR}/cache")

"""**Preprocess / Tokenization function**"""

max_input = 128
max_output = 32

def preprocess(batch):
    inputs = ["summarize: " + x for x in batch["article"]]

    model_inputs = tokenizer(
        inputs,
        max_length=max_input,
        truncation=True,
        padding="max_length"
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            batch["summary"],
            max_length=max_output,
            truncation=True,
            padding="max_length"
        )

    labels["input_ids"] = [
        [(token if token != tokenizer.pad_token_id else -100) for token in seq]
        for seq in labels["input_ids"]
    ]

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_ds = train_ds.map(preprocess, batched=True)
val_ds = val_ds.map(preprocess, batched=True)

"""**Data collator**"""

from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=True,
    label_pad_token_id=-100
)

"""**TrainingArguments (save everything into Drive)**"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=f"{BASE_DIR}/checkpoints",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=3e-4,
    num_train_epochs=5,

    save_strategy="epoch",
    eval_strategy="epoch", # Corrected argument name

    logging_dir=f"{BASE_DIR}/logs",
    logging_steps=100,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",

    report_to="none"  # disable W&B
)

"""**Trainer setup**"""

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=data_collator,
    tokenizer=tokenizer
)

"""**Train & Save final model to Drive**"""

trainer.train()

trainer.save_model(f"{BASE_DIR}/model")
tokenizer.save_pretrained(f"{BASE_DIR}/model")

"""**Test summary**"""

def summarize(text):
    inp = "summarize: " + text
    inputs = tokenizer(inp, return_tensors="pt", truncation=True)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}
    output = model.generate(inputs["input_ids"], max_length=32, num_beams=4)
    return tokenizer.decode(output[0], skip_special_tokens=True)

print("ARTICLE:", val_df.iloc[0]["article"])
print("GENERATED:", summarize(val_df.iloc[0]["article"]))
print("TRUE:", val_df.iloc[0]["summary"])